// Read contracts for the paginated supply queries. Nullable view fields stay explicit.
export type SupplyRows = {
  abastecimento_acordo: {
    id: string;
    unit_id: string;
    fornecedor_raiz: string;
    pratos_liberados: string[];
    entrada_divida_rs: number;
    compra_nova_rs: number;
    frete_rs: number;
    desembolso_total_rs: number | null;
    data_entrega: string | null;
    entrega_confirmada: boolean;
    qualidade_confirmada: boolean;
    todos_insumos_confirmados: boolean;
    quantidade_confirmada: string | null;
    alternativa_homologada: string | null;
    prazo_recebimento_dias: number;
    contribuicao_recuperavel_7d: number | null;
    contribuicao_recuperavel_14d: number | null;
    status: string;
    criado_por: string;
    criado_em: string;
    atualizado_em: string;
  };
  cardapio_papel: {
    produto_venda_ficha_id: string;
    unit_id: string;
    papel: string;
    aprovado_por: string;
    aprovado_em: string;
    retirada_solicitada_em: string | null;
    retirada_aprovada_em: string | null;
    retirada_motivo: string | null;
  };
  produto_venda_ficha: {
    id: string;
    unit_id: string;
    nome_venda: string;
    nome_venda_original: string | null;
    ficha_id: string | null;
    item_pai_id: string | null;
    origem: string;
    status: string;
    similaridade: number | null;
    sugestoes: unknown;
    receita_12m: number;
    qtd_12m: number;
    confirmado_por: string | null;
    confirmado_em: string | null;
    criado_em: string;
    atualizado_em: string;
  };
  v_abastecimento_contribuicao: {
    produto_venda_ficha_id: string;
    unit_id: string;
    dias_disponiveis: number | null;
    contribuicao_dia: number | null;
  };
  v_abastecimento_fila: {
    id: string;
    op_86_id: string | null;
    unit_id: string;
    produto_venda_ficha_id: string | null;
    tipo: string | null;
    causa: string | null;
    insumo_id: string | null;
    fornecedor_raiz: string | null;
    responsavel: string | null;
    proxima_acao: string | null;
    prazo: string | null;
    previsao_retorno: string | null;
    status: string;
    sugestao_prato_id: string | null;
    sugestao_insumo_id: string | null;
    sugestao_fornecedor_raiz: string | null;
    sugestao_causa: string | null;
    sugestao_detalhe: string | null;
    inicio_confirmado_em: string | null;
    causa_confirmada_por: string | null;
    causa_confirmada_em: string | null;
    retomada_cozinha_em: string | null;
    retomada_cozinha_por: string | null;
    retomada_pdv_em: string | null;
    criado_por: string | null;
    criado_em: string | null;
    atualizado_em: string | null;
    produto_nome: string | null;
    motivo_original: string | null;
    observacao: string | null;
    periodo: string | null;
    dia: string;
    relatorio_status: string | null;
    prato_sugerido: string | null;
    insumo_sugerido: string | null;
    fornecedor_nome: string | null;
    ultima_nota: string | null;
    vencido_rs: number | null;
    papel: string | null;
  };
  v_abastecimento_kpi: {
    unit_id: string;
    semana: string;
    registros: number | null;
    produtos_ruptura: number | null;
    causa_dono_pct: number | null;
    retomada_horas: number | null;
    retomada_assinatura_horas: number | null;
    com_pedido_pct: number | null;
    prazo_dias: number | null;
    vencido_assinatura_atual: number | null;
    cobertura_custo_pct: number | null;
    atualizado_em: string | null;
  };
  v_abastecimento_titulos: {
    id: string;
    unit_id: string;
    nr_titulo: number | null;
    nr_nota: number | null;
    nr_parcela: number | null;
    dt_documento: string | null;
    dt_vencimento: string | null;
    vl_saldo: number | null;
    vl_titulo: number | null;
    at_situacao: number | null;
    fornecedor_raiz: string;
    fornecedor_nome: string | null;
    dias_atraso: number | null;
    conciliar: boolean | null;
  };
};
